### ISSUE TITLE
[feature request] Add a context menu button

### ISSUE THREAD

**Issue by tubbadu** [igorlogius/fwdl#2]

**Comment by igorlogius** [comment]
I assume the context menu entry should be availbe for `a(nchor)` element  to directly pass targets (href) to the fwdl script/programm ..

BUT i already created an addon which provides exaclty this functionality: 
ref. https://github.com/igorlogius/handle-with

so i'm actually against adding the same to this one too.

**Comment by igorlogius** [comment]
@tubbadu 

Hope you dont mind ... too much, but i think this function does not belong into this addon, since it is more of a  "**download interception**"- handler. 

Of course if you think you can make a valid argument why this function does fit, please try explaining it to me.  - Would not be the first time i was convinced to adding something i initally though would not belong into an addon i created.

**Comment by tubbadu** [comment]
Of course no problem you're right!
